=== Monika-After-Story/MonikaModDev/schemas/v3/acs-split.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "title": "ACS (Split)",
    "description": "Monika After Story Mod split ACS JSON schema",

    "type": "object",
    "additionalProperties": false,

    "if": {
        "anyOf": [
            { "properties": { "rec_layer": { "const": 8 } } },
            { "properties": { "rec_layer": { "const": 9 } } }
        ]
    },
    "then": {
        "required": [
            "version",
            "type",
            "name",
            "img_sit",
            "pose_map",
            "arm_split"
        ]
    },
    "else": {
        "required": [
            "version",
            "type",
            "name",
            "img_sit",
            "pose_map"
        ]
    },

    "properties": {
        "__author": { "$ref": "#/$defs/any" },

        "version": { "const": 3 },
        "type":    { "const": 0 },
        "name":    { "type": "string" },
        "img_sit": { "$ref": "#/$defs/filename" },

        "pose_map": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mpm_type":      { "type": "integer" },
                "default":       { "$ref": "#/$defs/pose" },
                "l_default":     { "$ref": "#/$defs/pose" },
                "use_reg_for_l": { "type": "boolean", "default": false }
            },
            "patternProperties": {
                "p[0-7]": { "$ref": "#/$defs/pose" }
            }
        },

        "arm_split": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mpm_type":      { "type": "integer" },
                "default":       { "$ref": "#/$defs/acs_split_pose" },
                "l_default":     { "$ref": "#/$defs/acs_split_pose" },
                "use_reg_for_l": { "type": "boolean", "default": false }
            },
            "patternProperties": {
                "p[0-7]": { "$ref": "#/$defs/acs_split_pose" }
            }
        },

        "stay_on_start": { "type": "boolean", "default": false },

        "ex_props": {
            "type": "object",
            "default": { },
            "properties": {
                "drink":               { "$ref": "#/$defs/flag" },
                "excluded-hair-props": { "$ref": "#/$defs/string_list" },
                "food":                { "$ref": "#/$defs/flag" },
                "left-desk-acs":       { "$ref": "#/$defs/flag" },
                "required-hair-prop":  { "type": "string" },
                "ribbon-like":         { "$ref": "#/$defs/flag" },
                "twin-ribbon":         { "$ref": "#/$defs/flag" }
            }
        },

        "select_info": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "display_name":        { "type": "string" },
                "thumb":               { "$ref": "#/$defs/filename" },
                "group":               { "type": "string" },
                "visible_when_locked": { "type": "boolean", "default": true },
                "select_dlg":          { "$ref": "#/$defs/string_list" }
            }
        },

        "highlight": {
            "type": "object",
            "additionalProperties": false,

            "properties": {
                "default": { "$ref": "#/$defs/filter" },
                "mapping": {
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": { "^.*$": { "$ref": "#/$defs/filter" } }
                }
            }
        },

        "dryrun":       { "$ref": "#/$defs/flag" },
        "rec_layer":    { "enum": [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ], "default": 2 },
        "priority":     { "type": "integer", "default": 10 },
        "acs_type":     { "type": "string", "default": null },
        "mux_type":     { "$ref": "#/$defs/string_list" },
        "giftname":     { "$ref": "#/$defs/filename" },
        "dlg_desc":     { "type": "string", "pattern": "^[^A-Z]*$" },
        "dlg_plural":   { "type": "boolean" },
        "keep_on_desk": { "type": "boolean", "default": false }
    },

    "$defs": {
        "pose": { "type": "string", "default": null },
        "acs_split_pose": {
            "type": "string", "pattern": "^(?:|\\*|(?:(?:0|1|5|10))(?:\\^(?:0|1|5|10))*)$", "default": null
        },

        "flag": { },

        "string_list": { "type": "array","items": { "type": "string" }, "default": null },

        "filter":  {
            "type": "object",
            "properties": {
                "default": { "type": "string" },
                "day":     { "type": "string" },
                "night":   { "type": "string" }
            }
        },

        "filename": { "type": "string", "pattern": "^[^./\\\\]*$" },

        "any": { "type": [ "number", "string", "boolean", "object", "array", "null" ] }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/historyvariety_necklaces/Triforce Necklace/mod_assets/monika/j/historyvariety_triforce_necklace.json
{
    "__author": "HistoryVariety",
    "version": 3,
    "type": 0,
    "name": "historyvariety_triforce_necklace",
    "img_sit": "historyvariety_triforce_necklace",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 8,
    "acs_type": "necklace",
    "stay_on_start": true,
    "priority": 8,
    "dlg_desc": "necklace",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Triforce Necklace",
        "thumb": "historyvariety_triforce_necklace",
        "group": "necklace",
        "select_dlg": [
            "It's dangerous to go alone, take this!"
        ]
    },
    "giftname": "triforce_necklace",
    "arm_split": {
        "default": "0",
        "use_reg_for_l": true
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/unreleased/briaryoung/briaryoung-acs-earrings-danglies/mod_assets/monika/j/briaryoung-acs_earrings_danglies.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 0,
    "name": "briaryoung_earrings_danglies",
    "img_sit": "briaryoung_earrings_danglies",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 10,
    "acs_type": "earrings",
    "mux_type": [
        "earrings"
    ],
    "stay_on_start": true,
    "giftname": "danglyearrings",
    "dlg_desc": "dangly earrings",
    "dlg_plural": true,
    "select_info": {
        "display_name": "Dangly earrings",
        "thumb": "briaryoung_earrings_danglies",
        "group": "earrings",
        "select_dlg": [
            "Cute huh?"
        ]
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-mini ribbons/mod_assets/monika/j/briaryoung_acs_mini_ribbon_sky_blue.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 0,
    "name": "briaryoung_mini_ribbon_sky_blue",
    "img_sit": "briaryoung_mini_ribbon_sky_blue",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "mini-ribbon",
    "stay_on_start": true,
    "dlg_desc": "sky blue ribbon",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Ribbon (Sky blue, mini)",
        "thumb": "briaryoung_mini_ribbon_sky_blue",
        "group": "ribbon",
        "select_dlg": [
            "Just like the sky!"
        ]
    },
    "giftname": "miniskyblueribbon"
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/velius94/Velius94-STypeRibbons/mod_assets/monika/j/velius94_acs_ribbon_silver.json
{
    "__author": "Velius94",
    "version": 3,
    "type": 0,
    "name": "velius94_ribbon_silver",
    "img_sit": "velius94_ribbon_silver",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "s-type-ribbon",
    "stay_on_start": true,
    "select_info": {
        "display_name": "Ribbon (Silver, s-type)",
        "thumb": "velius94_ribbon_silver",
        "group": "ribbon",
        "select_dlg": [
            "Nice choice, [player]."
        ]
    },
    "giftname": "stypesilverribbon"
}

=== Monika-After-Story/MonikaModDev/spritepacks/unreleased/briaryoung/briaryoung-acs-earrings-musicnotes/mod_assets/monika/j/briaryoung-acs-earrings_musicnotes.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 0,
    "name": "briaryoung_earrings_musicnotes",
    "img_sit": "briaryoung_earrings_musicnotes",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 10,
    "acs_type": "earrings",
    "mux_type": [
        "earrings"
    ],
    "stay_on_start": true,
    "giftname": "musicnoteearrings",
    "dlg_desc": "music note earrings",
    "dlg_plural": true,
    "select_info": {
        "display_name": "Music note earrings",
        "thumb": "briaryoung_earrings_musicnotes",
        "group": "earrings",
        "select_dlg": [
            "Cute huh?"
        ]
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-mini ribbons/mod_assets/monika/j/briaryoung_acs_mini_ribbon_yellow.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 0,
    "name": "briaryoung_mini_ribbon_yellow",
    "img_sit": "briaryoung_mini_ribbon_yellow",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "mini-ribbon",
    "stay_on_start": true,
    "dlg_desc": "yellow ribbon",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Ribbon (Yellow, mini)",
        "thumb": "briaryoung_mini_ribbon_yellow",
        "group": "ribbon",
        "select_dlg": [
            "Like a sunny day!"
        ]
    },
    "giftname": "miniyellowribbon"
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/retrolovania/retrolovania-moreretroribbons/mod_assets/monika/j/retroadamshow_acs_ribbon_gb_green_retro.json
{
    "__author": "retroadamshow",
    "version": 3,
    "type": 0,
    "name": "retro_ribbon_gb_green",
    "img_sit": "retro_ribbon_gb_green",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "ribbon",
    "stay_on_start": true,
    "giftname": "gameboygreenribbon",
    "dlg_desc": "Game Boy-style green ribbon",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Ribbon (Game Boy Green) ",
        "thumb": "retro_ribbon_gb_green",
        "group": "ribbon",
        "select_dlg": [
            "How nostalgic!"
        ]
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/anonymioo/anonymioo-ribbons/mod_assets/monika/j/anonymioo_acs_ribbon_transexualpride.json
{
    "__author": "anonymioo",
    "version": 3,
    "type": 0,
    "name": "anonymioo_ribbon_transexualpride",
    "img_sit": "anonymioo_ribbon_transexualpride",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "ribbon",
    "stay_on_start": true,
    "dlg_desc": "transgender-pride-themed ribbon",
    "dlg_plural": false,
    "ex_props": {
        "transexualpride": true,
        "ribbon-multicolor": true
    },
    "select_info": {
        "display_name": "Ribbon (Transgender Pride Themed)",
        "thumb": "anonymioo_ribbon_transexualpride",
        "group": "ribbon"
    },
    "giftname": "transgenderpridethemedribbon"
}
