=== Monika-After-Story/MonikaModDev/schemas/v3/acs-split.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "title": "ACS (Split)",
    "description": "Monika After Story Mod split ACS JSON schema",

    "type": "object",
    "additionalProperties": false,

    "if": {
        "anyOf": [
            { "properties": { "rec_layer": { "const": 8 } } },
            { "properties": { "rec_layer": { "const": 9 } } }
        ]
    },
    "then": {
        "required": [
            "version",
            "type",
            "name",
            "img_sit",
            "pose_map",
            "arm_split"
        ]
    },
    "else": {
        "required": [
            "version",
            "type",
            "name",
            "img_sit",
            "pose_map"
        ]
    },

    "properties": {
        "__author": { "$ref": "#/$defs/any" },

        "version": { "const": 3 },
        "type":    { "const": 0 },
        "name":    { "type": "string" },
        "img_sit": { "$ref": "#/$defs/filename" },

        "pose_map": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mpm_type":      { "type": "integer" },
                "default":       { "$ref": "#/$defs/pose" },
                "l_default":     { "$ref": "#/$defs/pose" },
                "use_reg_for_l": { "type": "boolean", "default": false }
            },
            "patternProperties": {
                "p[0-7]": { "$ref": "#/$defs/pose" }
            }
        },

        "arm_split": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mpm_type":      { "type": "integer" },
                "default":       { "$ref": "#/$defs/acs_split_pose" },
                "l_default":     { "$ref": "#/$defs/acs_split_pose" },
                "use_reg_for_l": { "type": "boolean", "default": false }
            },
            "patternProperties": {
                "p[0-7]": { "$ref": "#/$defs/acs_split_pose" }
            }
        },

        "stay_on_start": { "type": "boolean", "default": false },

        "ex_props": {
            "type": "object",
            "default": { },
            "properties": {
                "drink":               { "$ref": "#/$defs/flag" },
                "excluded-hair-props": { "$ref": "#/$defs/string_list" },
                "food":                { "$ref": "#/$defs/flag" },
                "left-desk-acs":       { "$ref": "#/$defs/flag" },
                "required-hair-prop":  { "type": "string" },
                "ribbon-like":         { "$ref": "#/$defs/flag" },
                "twin-ribbon":         { "$ref": "#/$defs/flag" }
            }
        },

        "select_info": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "display_name":        { "type": "string" },
                "thumb":               { "$ref": "#/$defs/filename" },
                "group":               { "type": "string" },
                "visible_when_locked": { "type": "boolean", "default": true },
                "select_dlg":          { "$ref": "#/$defs/string_list" }
            }
        },

        "highlight": {
            "type": "object",
            "additionalProperties": false,

            "properties": {
                "default": { "$ref": "#/$defs/filter" },
                "mapping": {
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": { "^.*$": { "$ref": "#/$defs/filter" } }
                }
            }
        },

        "dryrun":       { "$ref": "#/$defs/flag" },
        "rec_layer":    { "enum": [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ], "default": 2 },
        "priority":     { "type": "integer", "default": 10 },
        "acs_type":     { "type": "string", "default": null },
        "mux_type":     { "$ref": "#/$defs/string_list" },
        "giftname":     { "$ref": "#/$defs/filename" },
        "dlg_desc":     { "type": "string", "pattern": "^[^A-Z]*$" },
        "dlg_plural":   { "type": "boolean" },
        "keep_on_desk": { "type": "boolean", "default": false }
    },

    "$defs": {
        "pose": { "type": "string", "default": null },
        "acs_split_pose": {
            "type": "string", "pattern": "^(?:|\\*|(?:(?:0|1|5|10))(?:\\^(?:0|1|5|10))*)$", "default": null
        },

        "flag": { },

        "string_list": { "type": "array","items": { "type": "string" }, "default": null },

        "filter":  {
            "type": "object",
            "properties": {
                "default": { "type": "string" },
                "day":     { "type": "string" },
                "night":   { "type": "string" }
            }
        },

        "filename": { "type": "string", "pattern": "^[^./\\\\]*$" },

        "any": { "type": [ "number", "string", "boolean", "object", "array", "null" ] }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-mini ribbons/mod_assets/monika/j/briaryoung_acs_mini_ribbon_pale_green.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 0,
    "name": "briaryoung_mini_ribbon_pale_green",
    "img_sit": "briaryoung_mini_ribbon_pale_green",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "mini-ribbon",
    "stay_on_start": true,
    "dlg_desc": "pale green ribbon",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Ribbon (Pale green, mini)",
        "thumb": "briaryoung_mini_ribbon_pale_green",
        "group": "ribbon",
        "select_dlg": [
            "I'm always a fan of green!"
        ]
    },
    "giftname": "minipalegreenribbon"
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/retrolovania/retrolovania-retroribbons/mod_assets/monika/j/retroadamshow_acs_bow_emerald_retro.json
{
    "__author": "retroadamshow",
    "version": 3,
    "type": 0,
    "name": "retro_bow_emerald",
    "img_sit": "retro_ribbon_emerald",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "ribbon",
    "mux_type": [
        "ribbon"
    ],
    "stay_on_start": true,
    "giftname": "8emeraldribbon",
    "dlg_desc": "8-bit emerald ribbon",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Ribbon (8-bit Emerald)",
        "thumb": "retro_ribbon_emerald",
        "group": "ribbon",
        "select_dlg": [
            "How nostalgic!"
        ]
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/historyvariety_necklaces/Animal Crossing/mod_assets/monika/j/historyvariety_animalcrossing_necklace.json
{
    "__author": "HistoryVariety",
    "version": 3,
    "type": 0,
    "name": "historyvariety_animalcrossing_necklace",
    "img_sit": "historyvariety_animalcrossing_necklace",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 8,
    "acs_type": "necklace",
    "stay_on_start": true,
    "priority": 8,
    "dlg_desc": "necklace",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Animal Crossing Necklace",
        "thumb": "historyvariety_animalcrossing_necklace",
        "group": "necklace",
        "select_dlg": [
            "Who's your favorite villager, [player]?"
        ]
    },
    "giftname": "animalcrossing_necklace",
    "arm_split": {
        "default": "0",
        "use_reg_for_l": true
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-acs-earrings-blacksilver-piercings/mod_assets/monika/j/briaryoung-acs-earrings-piercings.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 0,
    "name": "briaryoung_blacksilver_piercings",
    "img_sit": "briaryoung_blacksilver_piercings",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 10,
    "acs_type": "earrings",
    "mux_type": [
        "earrings"
    ],
    "stay_on_start": true,
    "giftname": "blacksilverpiercings",
    "dlg_desc": "black silver piercings",
    "dlg_plural": true,
    "select_info": {
        "display_name": "Piercings (Black-silver)",
        "thumb": "briaryoung_blacksilver_piercings",
        "group": "earrings",
        "select_dlg": [
            "Cute huh?"
        ]
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/retrolovania/retrolovania-nesbows/mod_assets/monika/j/retroadamshow_acs_bow_blue_retro.json
{
    "__author": "retroadamshow",
    "version": 3,
    "type": 0,
    "name": "retro_bow_blue",
    "img_sit": "retro_ribbon_blue",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "ribbon",
    "stay_on_start": true,
    "giftname": "8blueribbon",
    "dlg_desc": "8-bit blue ribbon",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Ribbon (8-bit Blue)",
        "thumb": "retro_ribbon_blue",
        "group": "ribbon",
        "select_dlg": [
            "How nostalgic!"
        ]
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-mini ribbons/mod_assets/monika/j/briaryoung_acs_mini_ribbon_purple.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 0,
    "name": "briaryoung_mini_ribbon_purple",
    "img_sit": "briaryoung_mini_ribbon_purple",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "mini-ribbon",
    "stay_on_start": true,
    "dlg_desc": "purple ribbon",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Ribbon (Purple, mini)",
        "thumb": "briaryoung_mini_ribbon_purple",
        "group": "ribbon",
        "select_dlg": [
            "Purple is such an elegant color!"
        ]
    },
    "giftname": "minipurpleribbon"
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-mini ribbons/mod_assets/monika/j/briaryoung_acs_mini_ribbon_dark_pink.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 0,
    "name": "briaryoung_mini_ribbon_dark_pink",
    "img_sit": "briaryoung_mini_ribbon_dark_pink",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "mini-ribbon",
    "stay_on_start": true,
    "dlg_desc": "dark pink ribbon",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Ribbon (Dark pink, mini)",
        "thumb": "briaryoung_mini_ribbon_dark_pink",
        "group": "ribbon",
        "select_dlg": [
            "Such a pretty color!"
        ]
    },
    "giftname": "minidarkpinkribbon"
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/velius94/Velius94-STypeRibbons/mod_assets/monika/j/velius94_acs_ribbon_sapphire.json
{
    "__author": "Velius94",
    "version": 3,
    "type": 0,
    "name": "velius94_ribbon_sapphire",
    "img_sit": "velius94_ribbon_sapphire",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "s-type-ribbon",
    "stay_on_start": true,
    "select_info": {
        "display_name": "Ribbon (Sapphire, s-type)",
        "thumb": "velius94_ribbon_sapphire",
        "group": "ribbon",
        "select_dlg": [
            "Nice choice, [player]!"
        ]
    },
    "giftname": "stypesapphireribbon"
}
