=== Monika-After-Story/MonikaModDev/schemas/v3/acs-split.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "title": "ACS (Split)",
    "description": "Monika After Story Mod split ACS JSON schema",

    "type": "object",
    "additionalProperties": false,

    "if": {
        "anyOf": [
            { "properties": { "rec_layer": { "const": 8 } } },
            { "properties": { "rec_layer": { "const": 9 } } }
        ]
    },
    "then": {
        "required": [
            "version",
            "type",
            "name",
            "img_sit",
            "pose_map",
            "arm_split"
        ]
    },
    "else": {
        "required": [
            "version",
            "type",
            "name",
            "img_sit",
            "pose_map"
        ]
    },

    "properties": {
        "__author": { "$ref": "#/$defs/any" },

        "version": { "const": 3 },
        "type":    { "const": 0 },
        "name":    { "type": "string" },
        "img_sit": { "$ref": "#/$defs/filename" },

        "pose_map": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mpm_type":      { "type": "integer" },
                "default":       { "$ref": "#/$defs/pose" },
                "l_default":     { "$ref": "#/$defs/pose" },
                "use_reg_for_l": { "type": "boolean", "default": false }
            },
            "patternProperties": {
                "p[0-7]": { "$ref": "#/$defs/pose" }
            }
        },

        "arm_split": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mpm_type":      { "type": "integer" },
                "default":       { "$ref": "#/$defs/acs_split_pose" },
                "l_default":     { "$ref": "#/$defs/acs_split_pose" },
                "use_reg_for_l": { "type": "boolean", "default": false }
            },
            "patternProperties": {
                "p[0-7]": { "$ref": "#/$defs/acs_split_pose" }
            }
        },

        "stay_on_start": { "type": "boolean", "default": false },

        "ex_props": {
            "type": "object",
            "default": { },
            "properties": {
                "drink":               { "$ref": "#/$defs/flag" },
                "excluded-hair-props": { "$ref": "#/$defs/string_list" },
                "food":                { "$ref": "#/$defs/flag" },
                "left-desk-acs":       { "$ref": "#/$defs/flag" },
                "required-hair-prop":  { "type": "string" },
                "ribbon-like":         { "$ref": "#/$defs/flag" },
                "twin-ribbon":         { "$ref": "#/$defs/flag" }
            }
        },

        "select_info": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "display_name":        { "type": "string" },
                "thumb":               { "$ref": "#/$defs/filename" },
                "group":               { "type": "string" },
                "visible_when_locked": { "type": "boolean", "default": true },
                "select_dlg":          { "$ref": "#/$defs/string_list" }
            }
        },

        "highlight": {
            "type": "object",
            "additionalProperties": false,

            "properties": {
                "default": { "$ref": "#/$defs/filter" },
                "mapping": {
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": { "^.*$": { "$ref": "#/$defs/filter" } }
                }
            }
        },

        "dryrun":       { "$ref": "#/$defs/flag" },
        "rec_layer":    { "enum": [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ], "default": 2 },
        "priority":     { "type": "integer", "default": 10 },
        "acs_type":     { "type": "string", "default": null },
        "mux_type":     { "$ref": "#/$defs/string_list" },
        "giftname":     { "$ref": "#/$defs/filename" },
        "dlg_desc":     { "type": "string", "pattern": "^[^A-Z]*$" },
        "dlg_plural":   { "type": "boolean" },
        "keep_on_desk": { "type": "boolean", "default": false }
    },

    "$defs": {
        "pose": { "type": "string", "default": null },
        "acs_split_pose": {
            "type": "string", "pattern": "^(?:|\\*|(?:(?:0|1|5|10))(?:\\^(?:0|1|5|10))*)$", "default": null
        },

        "flag": { },

        "string_list": { "type": "array","items": { "type": "string" }, "default": null },

        "filter":  {
            "type": "object",
            "properties": {
                "default": { "type": "string" },
                "day":     { "type": "string" },
                "night":   { "type": "string" }
            }
        },

        "filename": { "type": "string", "pattern": "^[^./\\\\]*$" },

        "any": { "type": [ "number", "string", "boolean", "object", "array", "null" ] }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/historyvariety_necklaces/Snail Shell Necklace/mod_assets/monika/j/historyvariety_snailshell_necklace.json
{
    "__author": "HistoryVariety",
    "version": 3,
    "type": 0,
    "name": "historyvariety_snailshell_necklace",
    "img_sit": "historyvariety_snailshell_necklace",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 8,
    "acs_type": "necklace",
    "stay_on_start": true,
    "priority": 8,
    "dlg_desc": "necklace",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Snail Shell Necklace",
        "thumb": "historyvariety_snailshell_necklace",
        "group": "necklace",
        "select_dlg": [
            "Perfect for the beach!"
        ]
    },
    "giftname": "snailshell_necklace",
    "arm_split": {
        "default": "0",
        "use_reg_for_l": true
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-mini ribbons/mod_assets/monika/j/briaryoung_acs_mini_ribbon_pink.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 0,
    "name": "briaryoung_mini_ribbon_pink",
    "img_sit": "briaryoung_mini_ribbon_pink",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "mini-ribbon",
    "stay_on_start": true,
    "dlg_desc": "pink ribbon",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Ribbon (Pink, mini)",
        "thumb": "briaryoung_mini_ribbon_pink",
        "group": "ribbon",
        "select_dlg": [
            "Cute!"
        ]
    },
    "giftname": "minipinkribbon"
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-mini ribbons/mod_assets/monika/j/briaryoung_acs_mini_ribbon_royal_blue.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 0,
    "name": "briaryoung_mini_ribbon_royal_blue",
    "img_sit": "briaryoung_mini_ribbon_royal_blue",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "mini-ribbon",
    "stay_on_start": true,
    "dlg_desc": "royal blue ribbon",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Ribbon (Royal blue, mini)",
        "thumb": "briaryoung_mini_ribbon_royal_blue",
        "group": "ribbon",
        "select_dlg": [
            "Blue is always a good choice!"
        ]
    },
    "giftname": "miniroyalblueribbon"
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/historyvariety_necklaces/Gold Chain Necklace/mod_assets/monika/j/historyvariety_goldchain_necklace.json
{
    "__author": "HistoryVariety",
    "version": 3,
    "type": 0,
    "name": "historyvariety_goldchain_necklace",
    "img_sit": "historyvariety_goldchain_necklace",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 8,
    "acs_type": "necklace",
    "stay_on_start": true,
    "priority": 8,
    "dlg_desc": "necklace",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Gold Chain Necklace",
        "thumb": "historyvariety_goldchain_necklace",
        "group": "necklace",
        "select_dlg": [
            "Oh! Are we going out somewhere, [player]?"
        ]
    },
    "giftname": "goldchain_necklace",
    "arm_split": {
        "default": "0",
        "use_reg_for_l": true
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-chokers-pack-01/mod_assets/monika/j/briaryoung_acs_choker_spiral_black.json
{
    "__author": "Briar Young",
    "version": 3,
    "type": 0,
    "name": "briaryoung_choker_spiral_black",
    "img_sit": "briaryoung_choker_spiral_black",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 8,
    "acs_type": "choker",
    "stay_on_start": true,
    "priority": 8,
    "dlg_desc": "choker",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Choker (Spiral, Black)",
        "thumb": "briaryoung_choker_spiral_black",
        "group": "choker"
    },
    "giftname": "chokerspiralblack",
    "arm_split": {
        "default": "0",
        "use_reg_for_l": true
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/unreleased/briaryoung/briaryoung-acs-earrings-hoops-gold/mod_assets/monika/j/briaryoung-acs-earrings_hoops_gold.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 0,
    "name": "briaryoung_earrings_hoops_gold",
    "img_sit": "briaryoung_earrings_hoops_gold",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 10,
    "acs_type": "earrings",
    "mux_type": [
        "earrings"
    ],
    "stay_on_start": true,
    "giftname": "goldhoopearrings",
    "dlg_desc": "gold hoop earrings",
    "dlg_plural": true,
    "select_info": {
        "display_name": "Hoop earrings (gold)",
        "thumb": "briaryoung_earrings_hoops_gold",
        "group": "earrings",
        "select_dlg": [
            "Cute huh?"
        ]
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/retrolovania/retrolovania-moreretroribbons/mod_assets/monika/j/retroadamshow_acs_ribbon_red_retro.json
{
    "__author": "retroadamshow",
    "version": 3,
    "type": 0,
    "name": "retro_ribbon_red",
    "img_sit": "retro_ribbon_red",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "ribbon",
    "stay_on_start": true,
    "giftname": "8redribbon",
    "dlg_desc": "8-bit red ribbon",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Ribbon (8-bit Red)",
        "thumb": "retro_ribbon_red",
        "group": "ribbon",
        "select_dlg": [
            "How nostalgic!"
        ]
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-mini ribbons/mod_assets/monika/j/briaryoung_acs_mini_ribbon_orange.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 0,
    "name": "briaryoung_mini_ribbon_orange",
    "img_sit": "briaryoung_mini_ribbon_orange",
    "pose_map": {
        "default": "0",
        "l_default": "5"
    },
    "rec_layer": 3,
    "acs_type": "mini-ribbon",
    "stay_on_start": true,
    "dlg_desc": "orange ribbon",
    "dlg_plural": false,
    "select_info": {
        "display_name": "Ribbon (Orange, mini)",
        "thumb": "briaryoung_mini_ribbon_orange",
        "group": "ribbon",
        "select_dlg": [
            "Reminds me of fall!"
        ]
    },
    "giftname": "miniorangeribbon"
}
