=== Monika-After-Story/MonikaModDev/schemas/v3/clothes.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "title": "Clothes",
    "description": "Monika After Story Mod clothes JSON schema",

    "type": "object",
    "additionalProperties": false,
    "required": [
        "version",
        "type",
        "name",
        "img_sit",
        "pose_map"
    ],

    "properties": {
        "__author": { "$ref": "#/$defs/any" },

        "version": { "const": 3 },
        "type":    { "const": 2 },
        "name":    { "type": "string" },
        "img_sit": { "$ref": "#/$defs/filename" },

        "pose_map": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mpm_type":      { "type": "integer" },
                "default":       { "$ref": "#/$defs/pose" },
                "l_default":     { "$ref": "#/$defs/pose" },
                "use_reg_for_l": { "type": "boolean", "default": false }
            },
            "patternProperties": {
                "p[0-7]": { "$ref": "#/$defs/pose" }
            }
        },

        "stay_on_start": { "type": "boolean", "default": false },

        "ex_props": {
            "type": "object",
            "default": { },
            "properties": {
                "excluded-clothes-props": { "$ref": "#/$defs/string_list" },
                "no-tails":               { "$ref": "#/$defs/flag" },
                "required-clothes-prop":  { "type": "string" },
                "ribbon":                 { "$ref": "#/$defs/flag" },
                "ribbon-off":             { "$ref": "#/$defs/flag" },
                "ribbon-restore":         { "$ref": "#/$defs/flag" },
                "tiedstrand":             { "$ref": "#/$defs/flag" },
                "twintails":              { "$ref": "#/$defs/flag" }
            }
        },

        "select_info": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "display_name":        { "type": "string" },
                "thumb":               { "$ref": "#/$defs/filename" },
                "group":               { "type": "string" },
                "visible_when_locked": { "type": "boolean", "default": true },
                "select_dlg":          { "$ref": "#/$defs/string_list" }
            }
        },

        "highlight": {
            "type": "object",
            "additionalProperties": false,

            "properties": {
                "default": { "$ref": "#/$defs/filter" },
                "mapping": {
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": { "^.*$": { "$ref": "#/$defs/filter" } }
                }
            }
        },

        "dryrun": { "$ref": "#/$defs/flag" },

        "hair_map": {
            "type": "object",
            "properties": {
                "all": { "type": "string", "default": "def" }
            },
            "patternProperties": {
                "^.*$": { "type": "string" }
            }
        },

        "giftname": { "$ref": "#/$defs/filename" },

        "pose_arms": {
            "crossed":             { "$ref": "#/$defs/pose_arm" },
            "left-down":           { "$ref": "#/$defs/pose_arm" },
            "left-rest":           { "$ref": "#/$defs/pose_arm" },
            "right-down":          { "$ref": "#/$defs/pose_arm" },
            "right-point":         { "$ref": "#/$defs/pose_arm" },
            "right-restpoint":     { "$ref": "#/$defs/pose_arm" },
            "steepling":           { "$ref": "#/$defs/pose_arm" },
            "def|left-down":       { "$ref": "#/$defs/pose_arm" },
            "def|right-def":       { "$ref": "#/$defs/pose_arm" }
        }
    },

    "$defs": {
        "pose": {
            "anyOf": [
                {
                    "if":   { "properties": { "mpm_type": { "const": 0 } } },
                    "then": { "type": "boolean" }
                },
                {
                    "if":   { "properties": { "mpm_type": { "const": 1 } } },
                    "then": {
                        "enum": [
                            "steepling", "crossed", "restleftpointright", "pointright", "down", "downleftpointright", "def|def"
                        ]
                    }
                }
            ]
        },

        "flag": { },

        "string_list": { "type": "array","items": { "type": "string" }, "default": null },

        "filter":  {
            "type": "object",
            "properties": {
                "default": { "type": "string" },
                "day":     { "type": "string" },
                "night":   { "type": "string" }
            }
        },

        "filename": { "type": "string", "pattern": "^[^./\\\\]*$" },

        "pose_arm": {
            "type": "object",
            "required": [ "tag", "layers" ],
            "properties": {
                "tag": { "type": "string", "pattern": "^arms-(?:left|right)-" },
                "layers": {
                    "type": "string", "pattern": "^(?:|\\*|(?:(?:0|1|5|10))(?:\\^(?:0|1|5|10))*)$"
                },
                "highlight": {
                    "type": "object",
                    "additionalProperties": false,

                    "properties": {
                        "default": { "$ref": "#/$defs/filter" },
                        "mapping": {
                            "type": "object",
                            "additionalProperties": false,
                            "patternProperties": { "^.*$": { "$ref": "#/$defs/filter" } }
                        }
                    }
                }
            }
        },

        "any": { "type": [ "number", "string", "boolean", "object", "array", "null" ] }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/unreleased/briaryoung/briaryoung-tied crop top white/mod_assets/monika/j/briaryoung_clothes_tied_crop_top_white.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 2,
    "name": "briaryoung_tied_crop_top_white",
    "img_sit": "briaryoung_tied_crop_top_white",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "compat-downtiedstrand": true
    },
    "select_info": {
        "display_name": "Tied Crop Top (White)",
        "thumb": "briaryoung_tied_crop_top_white",
        "group": "clothes",
        "select_dlg": [
            "Cute and casual!"
        ]
    },
    "giftname": "tiedcroptopwhite",
    "pose_arms": {}
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/orca/Orcaramelo-shellbikini/mod_assets/monika/j/orcaramelo_clothes_bikini_shell.json
{
    "__author": "Orcaramelo",
    "version": 3,
    "type": 2,
    "name": "orcaramelo_bikini_shell",
    "img_sit": "orcaramelo_bikini_shell",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "bikini": true,
        "bare-shoulders": true
    },
    "select_info": {
        "display_name": "Bikini (Shell)",
        "thumb": "orcaramelo_bikini_shell",
        "group": "clothes",
        "select_dlg": [
            "Seashells seashells, by the sea shore~",
            "Who says mermaids aren't real?"
        ]
    },
    "giftname": "shellbikini",
    "pose_arms": {}
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-chika fujiwara/mod_assets/monika/j/briaryoung_clothes_shuchiin_academy_uniform.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 2,
    "name": "briaryoung_shuchiin_academy_uniform",
    "img_sit": "briaryoung_shuchiin_academy_uniform",
    "pose_map": {
        "mpm_type": 0,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true
    },
    "stay_on_start": true,
    "ex_props": {
        "desired-hair-prop": "straight-bangs",
        "costume": "o31",
        "cosplay": true
    },
    "select_info": {
        "display_name": "Shuchi'in Academy Uniform",
        "thumb": "briaryoung_shuchiin_academy_uniform",
        "group": "clothes",
        "select_dlg": [
            "I detect love nearby~"
        ]
    },
    "pose_arms": {
        "crossed": {
            "tag": "crossed",
            "layers": "5"
        },
        "left-down": {
            "tag": "down",
            "layers": "0"
        },
        "left-rest": {
            "tag": "rest",
            "layers": "10"
        },
        "right-down": {
            "tag": "down",
            "layers": "0"
        },
        "right-point": {
            "tag": "point",
            "layers": "0"
        },
        "right-restpoint": {
            "tag": "restpoint",
            "layers": "10"
        },
        "steepling": {
            "tag": "steepling",
            "layers": "10"
        },
        "def|left-def": {
            "tag": "def",
            "layers": "10"
        },
        "def|right-def": {
            "tag": "def",
            "layers": "5^10"
        }
    },
    "giftname": "shuchiinacademyuniform"
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/j/briaryoung_clothes_button_up_flowered.json
{
    "__author": "Briar Young",
    "ex_props": {
        "compat-downtiedstrand": true,
        "home": true,
        "date": true
    },
    "version": 3,
    "type": 2,
    "name": "briaryoung_button_up_flowered",
    "img_sit": "briaryoung_button_up_flowered",
    "pose_map": {
        "mpm_type": 0,
        "default": false,
        "use_reg_for_l": true,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true
    },
    "stay_on_start": true,
    "select_info": {
        "display_name": "Button Up (Flowered)",
        "thumb": "briaryoung_button_up_flowered",
        "group": "clothes",
        "select_dlg": [
            "I love all the flowers!",
            "Great choice, [player]!"
        ]
    },
    "giftname": "buttonupflowered",
    "pose_arms": {
        "crossed": {
            "tag": "crossed",
            "layers": "5"
        },
        "left-down": {
            "tag": "down",
            "layers": "0"
        },
        "left-rest": {
            "tag": "rest",
            "layers": "10"
        },
        "right-down": {
            "tag": "down",
            "layers": "0"
        },
        "right-point": {
            "tag": "point",
            "layers": "0"
        },
        "right-restpoint": {
            "tag": "restpoint",
            "layers": "10"
        },
        "steepling": {
            "tag": "steepling",
            "layers": "10"
        },
        "def|left-def": {
            "tag": "def",
            "layers": "10"
        },
        "def|right-def": {
            "tag": "def",
            "layers": "5"
        }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/finale/Finale-green-dress/mod_assets/monika/j/finale_clothes_green_dress.json
{
    "__author": "Finale",
    "ex_props": {
        "bare-shoulders": true,
        "home": true,
        "date": true
    },
    "version": 3,
    "type": 2,
    "name": "finale_green_dress",
    "img_sit": "finale_green_dress",
    "pose_map": {
        "mpm_type": 0,
        "default": false,
        "use_reg_for_l": true,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true
    },
    "stay_on_start": true,
    "select_info": {
        "display_name": "Dress (Green)",
        "thumb": "finale_green_dress",
        "group": "clothes",
        "select_dlg": [
            "How do I look, [player]?",
            "Pretty cute, right?",
            "Are we going somewhere special today?~"
        ]
    },
    "giftname": "greendress",
    "pose_arms": {
        "crossed": {
            "tag": "crossed",
            "layers": "5"
        },
        "left-down": {
            "tag": "down",
            "layers": "0"
        },
        "left-rest": {
            "tag": "rest",
            "layers": "10"
        },
        "right-down": {
            "tag": "down",
            "layers": "0"
        },
        "right-point": {
            "tag": "point",
            "layers": "0"
        },
        "right-restpoint": {
            "tag": "restpoint",
            "layers": "10"
        },
        "steepling": {
            "tag": "steepling",
            "layers": "10"
        },
        "def|left-def": {
            "tag": "def",
            "layers": "10"
        },
        "def|right-def": {
            "tag": "def",
            "layers": "5"
        }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/brairyoung-vcut crossed straps tanktop white/mod_assets/monika/j/briaryoung_clothes_vcut_crossed_straps_tanktop_white.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 2,
    "name": "briaryoung_vcut_crossed_straps_tanktop_white",
    "img_sit": "briaryoung_vcut_crossed_straps_tanktop_white",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "bare-shoulders": true
    },
    "select_info": {
        "display_name": "V-cut Crossed Straps Tanktop (White)",
        "thumb": "briaryoung_vcut_crossed_straps_tanktop_white",
        "group": "clothes",
        "select_dlg": [
            "How do I look?",
            "Perfect for a summer day."
        ]
    },
    "giftname": "vcutcrossedstrapstanktopwhite",
    "pose_arms": {}
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/mocca_bun/Mocca_bun-blackandwhitestripedpullover/mod_assets/monika/j/mocca_bun_blackandwhitestripedpullover.json
{
    "__author": [
        "multimokia",
        "mocca_bun"
    ],
    "ex_props": {
        "bare-shoulders": true
    },
    "version": 3,
    "type": 2,
    "name": "mocca_bun_blackandwhitestripedpullover",
    "img_sit": "mocca_bun_blackandwhitestripedpullover",
    "pose_map": {
        "mpm_type": 0,
        "default": false,
        "use_reg_for_l": true,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true
    },
    "stay_on_start": true,
    "select_info": {
        "display_name": "Pullover (Black and White Stripe)",
        "thumb": "mocca_bun_blackandwhitestripedpullover",
        "group": "clothes",
        "select_dlg": [
            "How do I look, [player]?",
            "Pretty cute, right?",
            "Great choice, [player]! This is so comfortable~"
        ]
    },
    "giftname": "blackandwhitestripedpullover",
    "pose_arms": {
        "crossed": {
            "tag": "crossed",
            "layers": "5"
        },
        "left-down": {
            "tag": "down",
            "layers": "0^5"
        },
        "left-rest": {
            "tag": "rest",
            "layers": "10"
        },
        "right-down": {
            "tag": "down",
            "layers": "0^5"
        },
        "right-point": {
            "tag": "point",
            "layers": "0"
        },
        "right-restpoint": {
            "tag": "restpoint",
            "layers": "10"
        },
        "steepling": {
            "tag": "steepling",
            "layers": "10"
        },
        "def|left-def": {
            "tag": "def",
            "layers": "10"
        },
        "def|right-def": {
            "tag": "def",
            "layers": "5"
        }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/hatana/hatana-2B/mod_assets/monika/j/hatana_clothes_yorha_2b_cosplay.json
{
    "__author": "hatana",
    "version": 3,
    "type": 2,
    "name": "hatana_2b",
    "img_sit": "hatana_2b",
    "pose_map": {
        "mpm_type": 0,
        "default": false,
        "l_default": false,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true
    },
    "stay_on_start": true,
    "ex_props": {
        "cosplay": true,
        "costume": "o31",
        "hide-ring": true
    },
    "select_info": {
        "display_name": "YoRHa No.2 Type B",
        "thumb": "hatana_2b",
        "group": "clothes"
    },
    "giftname": "2bcosplay",
    "pose_arms": {
        "crossed": {
            "tag": "crossed",
            "layers": "5^10"
        },
        "left-down": {
            "tag": "down",
            "layers": "0"
        },
        "left-rest": {
            "tag": "rest",
            "layers": "10"
        },
        "right-down": {
            "tag": "down",
            "layers": "0"
        },
        "right-point": {
            "tag": "point",
            "layers": "0"
        },
        "right-restpoint": {
            "tag": "restpoint",
            "layers": "10"
        },
        "steepling": {
            "tag": "steepling",
            "layers": "10"
        },
        "def|left-def": {
            "tag": "def",
            "layers": "10"
        },
        "def|right-def": {
            "tag": "def",
            "layers": "5^10"
        }
    }
}
