=== Monika-After-Story/MonikaModDev/schemas/v3/clothes.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "title": "Clothes",
    "description": "Monika After Story Mod clothes JSON schema",

    "type": "object",
    "additionalProperties": false,
    "required": [
        "version",
        "type",
        "name",
        "img_sit",
        "pose_map"
    ],

    "properties": {
        "__author": { "$ref": "#/$defs/any" },

        "version": { "const": 3 },
        "type":    { "const": 2 },
        "name":    { "type": "string" },
        "img_sit": { "$ref": "#/$defs/filename" },

        "pose_map": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mpm_type":      { "type": "integer" },
                "default":       { "$ref": "#/$defs/pose" },
                "l_default":     { "$ref": "#/$defs/pose" },
                "use_reg_for_l": { "type": "boolean", "default": false }
            },
            "patternProperties": {
                "p[0-7]": { "$ref": "#/$defs/pose" }
            }
        },

        "stay_on_start": { "type": "boolean", "default": false },

        "ex_props": {
            "type": "object",
            "default": { },
            "properties": {
                "excluded-clothes-props": { "$ref": "#/$defs/string_list" },
                "no-tails":               { "$ref": "#/$defs/flag" },
                "required-clothes-prop":  { "type": "string" },
                "ribbon":                 { "$ref": "#/$defs/flag" },
                "ribbon-off":             { "$ref": "#/$defs/flag" },
                "ribbon-restore":         { "$ref": "#/$defs/flag" },
                "tiedstrand":             { "$ref": "#/$defs/flag" },
                "twintails":              { "$ref": "#/$defs/flag" }
            }
        },

        "select_info": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "display_name":        { "type": "string" },
                "thumb":               { "$ref": "#/$defs/filename" },
                "group":               { "type": "string" },
                "visible_when_locked": { "type": "boolean", "default": true },
                "select_dlg":          { "$ref": "#/$defs/string_list" }
            }
        },

        "highlight": {
            "type": "object",
            "additionalProperties": false,

            "properties": {
                "default": { "$ref": "#/$defs/filter" },
                "mapping": {
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": { "^.*$": { "$ref": "#/$defs/filter" } }
                }
            }
        },

        "dryrun": { "$ref": "#/$defs/flag" },

        "hair_map": {
            "type": "object",
            "properties": {
                "all": { "type": "string", "default": "def" }
            },
            "patternProperties": {
                "^.*$": { "type": "string" }
            }
        },

        "giftname": { "$ref": "#/$defs/filename" },

        "pose_arms": {
            "crossed":             { "$ref": "#/$defs/pose_arm" },
            "left-down":           { "$ref": "#/$defs/pose_arm" },
            "left-rest":           { "$ref": "#/$defs/pose_arm" },
            "right-down":          { "$ref": "#/$defs/pose_arm" },
            "right-point":         { "$ref": "#/$defs/pose_arm" },
            "right-restpoint":     { "$ref": "#/$defs/pose_arm" },
            "steepling":           { "$ref": "#/$defs/pose_arm" },
            "def|left-down":       { "$ref": "#/$defs/pose_arm" },
            "def|right-def":       { "$ref": "#/$defs/pose_arm" }
        }
    },

    "$defs": {
        "pose": {
            "anyOf": [
                {
                    "if":   { "properties": { "mpm_type": { "const": 0 } } },
                    "then": { "type": "boolean" }
                },
                {
                    "if":   { "properties": { "mpm_type": { "const": 1 } } },
                    "then": {
                        "enum": [
                            "steepling", "crossed", "restleftpointright", "pointright", "down", "downleftpointright", "def|def"
                        ]
                    }
                }
            ]
        },

        "flag": { },

        "string_list": { "type": "array","items": { "type": "string" }, "default": null },

        "filter":  {
            "type": "object",
            "properties": {
                "default": { "type": "string" },
                "day":     { "type": "string" },
                "night":   { "type": "string" }
            }
        },

        "filename": { "type": "string", "pattern": "^[^./\\\\]*$" },

        "pose_arm": {
            "type": "object",
            "required": [ "tag", "layers" ],
            "properties": {
                "tag": { "type": "string", "pattern": "^arms-(?:left|right)-" },
                "layers": {
                    "type": "string", "pattern": "^(?:|\\*|(?:(?:0|1|5|10))(?:\\^(?:0|1|5|10))*)$"
                },
                "highlight": {
                    "type": "object",
                    "additionalProperties": false,

                    "properties": {
                        "default": { "$ref": "#/$defs/filter" },
                        "mapping": {
                            "type": "object",
                            "additionalProperties": false,
                            "patternProperties": { "^.*$": { "$ref": "#/$defs/filter" } }
                        }
                    }
                }
            }
        },

        "any": { "type": [ "number", "string", "boolean", "object", "array", "null" ] }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/unreleased/briaryoung/briaryoung-tied crop top black/mod_assets/monika/j/briaryoung_clothes_tied_crop_top_black.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 2,
    "name": "briaryoung_tied_crop_top_black",
    "img_sit": "briaryoung_tied_crop_top_black",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "compat-downtiedstrand": true
    },
    "select_info": {
        "display_name": "Tied Crop Top (Black)",
        "thumb": "briaryoung_tied_crop_top_black",
        "group": "clothes",
        "select_dlg": [
            "Cute and casual!"
        ]
    },
    "giftname": "tiedcroptopblack",
    "pose_arms": {}
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-sleeveless turtleneck black/mod_assets/monika/j/briaryoung_clothes_sleeveless_turtleneck_black.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 2,
    "name": "briaryoung_sleeveless_turtleneck_black",
    "img_sit": "briaryoung_sleeveless_turtleneck_black",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "compat-downtiedstrand": true
    },
    "select_info": {
        "display_name": "Sleeveless Turtleneck (Black)",
        "thumb": "briaryoung_sleeveless_turtleneck_black",
        "group": "clothes",
        "select_dlg": [
            "I love this look!"
        ]
    },
    "giftname": "sleevelessturtleneckblack",
    "pose_arms": {}
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/finale/Finale-tanktop/mod_assets/monika/j/finale_clothes_tanktop.json
{
    "__author": "Finale",
    "version": 3,
    "type": 2,
    "name": "finale_tanktop",
    "img_sit": "finale_tanktop",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "bare-shoulders": true
    },
    "select_info": {
        "display_name": "Tanktop (White)",
        "thumb": "finale_tanktop",
        "group": "clothes",
        "select_dlg": [
            "How do I look, [player]?",
            "Perfect for a hot day."
        ]
    },
    "giftname": "tanktop",
    "pose_arms": {}
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/velius94/Velius94-PinkShirt/mod_assets/monika/j/velius94_clothes_shirt_pink.json
{
    "__author": "Velius94",
    "version": 3,
    "type": 2,
    "name": "velius94_shirt_pink",
    "img_sit": "velius94_shirt_pink",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "bare-shoulders": true
    },
    "select_info": {
        "display_name": "Shirt (Pink)",
        "thumb": "velius94_shirt_pink",
        "group": "clothes",
        "select_dlg": [
            "Pretty in pink~"
        ]
    },
    "giftname": "pinkshirt",
    "pose_arms": {}
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-tuxedo-black/mod_assets/monika/j/briaryoung_clothes_tuxedo_black.json
{
    "__author": "briaryoung",
    "ex_props": {
        "jacket": true
    },
    "giftname": "blacktuxedo",
    "img_sit": "briaryoung_tuxedo_black",
    "name": "briaryoung_tuxedo_black",
    "pose_arms": {
        "crossed": {
            "layers": "5^10",
            "tag": "crossed"
        },
        "def|left-def": {
            "layers": "10",
            "tag": "def"
        },
        "def|right-def": {
            "layers": "5^10",
            "tag": "def"
        },
        "left-down": {
            "layers": "0",
            "tag": "down"
        },
        "left-rest": {
            "layers": "10",
            "tag": "rest"
        },
        "right-down": {
            "layers": "0",
            "tag": "down"
        },
        "right-point": {
            "layers": "0",
            "tag": "point"
        },
        "right-restpoint": {
            "layers": "10",
            "tag": "restpoint"
        },
        "steepling": {
            "layers": "10",
            "tag": "steepling"
        }
    },
    "pose_map": {
        "default": false,
        "mpm_type": 0,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true,
        "use_reg_for_l": true
    },
    "select_info": {
        "display_name": "Tuxedo (Black)",
        "group": "clothes",
        "select_dlg": [
            "Very formal!"
        ],
        "thumb": "briaryoung_tuxedo_black"
    },
    "stay_on_start": true,
    "type": 2,
    "version": 3
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/orca/Orcaramelo-shoulderless-sweater/mod_assets/monika/j/orcaramelo_clothes_sweater_shoulderless.json
{
    "__author": "Orcaramelo & moniking",
    "version": 3,
    "type": 2,
    "name": "orcaramelo_sweater_shoulderless",
    "img_sit": "orcaramelo_sweater_shoulderless",
    "pose_map": {
        "mpm_type": 0,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true
    },
    "stay_on_start": true,
    "ex_props": {
        "bare-shoulders": true
    },
    "select_info": {
        "display_name": "Sweater (Shoulderless)",
        "thumb": "orcaramelo_sweater_shoulderless",
        "group": "clothes",
        "select_dlg": [
            "Feels cozy~",
            "Fitting for a winter day!",
            "It's very warm..."
        ]
    },
    "giftname": "shoulderlesssweater",
    "pose_arms": {
        "crossed": {
            "tag": "crossed",
            "layers": "5^10"
        },
        "left-down": {
            "tag": "down",
            "layers": "0"
        },
        "left-rest": {
            "tag": "rest",
            "layers": "10"
        },
        "right-down": {
            "tag": "down",
            "layers": "0"
        },
        "right-point": {
            "tag": "point",
            "layers": "0"
        },
        "right-restpoint": {
            "tag": "restpoint",
            "layers": "10"
        },
        "steepling": {
            "tag": "steepling",
            "layers": "10"
        },
        "def|left-def": {
            "tag": "def",
            "layers": "10"
        },
        "def|right-def": {
            "tag": "def",
            "layers": "5^10"
        }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/finale/Finale-shirt-resthere/mod_assets/monika/j/finale_clothes_shirt_resthere.json
{
    "__author": "Finale",
    "version": 3,
    "type": 2,
    "name": "finale_shirt_resthere",
    "img_sit": "finale_shirt_resthere",
    "pose_map": {
        "mpm_type": 0,
        "default": false,
        "use_reg_for_l": true,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true
    },
    "stay_on_start": true,
    "select_info": {
        "display_name": "Shirt (Rest Here)",
        "thumb": "finale_shirt_resthere",
        "group": "clothes",
        "select_dlg": [
            "Great choice, [player]! This is so comfortable~",
            "I can't wait until you actually can rest your head here~"
        ]
    },
    "giftname": "resthereshirt",
    "pose_arms": {
        "crossed": {
            "tag": "crossed",
            "layers": "5"
        },
        "left-down": {
            "tag": "down",
            "layers": "0"
        },
        "left-rest": {
            "tag": "rest",
            "layers": "10"
        },
        "right-down": {
            "tag": "down",
            "layers": "0"
        },
        "right-point": {
            "tag": "point",
            "layers": "0"
        },
        "right-restpoint": {
            "tag": "restpoint",
            "layers": "10"
        },
        "steepling": {
            "tag": "steepling",
            "layers": "10"
        },
        "def|left-def": {
            "tag": "def",
            "layers": "10"
        },
        "def|right-def": {
            "tag": "def",
            "layers": "5"
        }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-dress dark blue sparkle/mod_assets/monika/j/briaryoung_clothes_dress_dark_blue_sparkle.json
{
    "__author": "Briar Young",
    "version": 3,
    "type": 2,
    "name": "briaryoung_dress_dark_blue_sparkle",
    "img_sit": "briaryoung_dress_dark_blue_sparkle",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "bikini": true,
        "bare-shoulders": true
    },
    "select_info": {
        "display_name": "Dress (Dark blue, sparkly)",
        "thumb": "briaryoung_dress_dark_blue_sparkle",
        "group": "clothes",
        "select_dlg": [
            "Glittery as the night sky~",
            "This is so pretty!"
        ]
    },
    "giftname": "dressdarkbluesparkle",
    "pose_arms": {}
}
