=== Monika-After-Story/MonikaModDev/schemas/v3/clothes.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "title": "Clothes",
    "description": "Monika After Story Mod clothes JSON schema",

    "type": "object",
    "additionalProperties": false,
    "required": [
        "version",
        "type",
        "name",
        "img_sit",
        "pose_map"
    ],

    "properties": {
        "__author": { "$ref": "#/$defs/any" },

        "version": { "const": 3 },
        "type":    { "const": 2 },
        "name":    { "type": "string" },
        "img_sit": { "$ref": "#/$defs/filename" },

        "pose_map": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mpm_type":      { "type": "integer" },
                "default":       { "$ref": "#/$defs/pose" },
                "l_default":     { "$ref": "#/$defs/pose" },
                "use_reg_for_l": { "type": "boolean", "default": false }
            },
            "patternProperties": {
                "p[0-7]": { "$ref": "#/$defs/pose" }
            }
        },

        "stay_on_start": { "type": "boolean", "default": false },

        "ex_props": {
            "type": "object",
            "default": { },
            "properties": {
                "excluded-clothes-props": { "$ref": "#/$defs/string_list" },
                "no-tails":               { "$ref": "#/$defs/flag" },
                "required-clothes-prop":  { "type": "string" },
                "ribbon":                 { "$ref": "#/$defs/flag" },
                "ribbon-off":             { "$ref": "#/$defs/flag" },
                "ribbon-restore":         { "$ref": "#/$defs/flag" },
                "tiedstrand":             { "$ref": "#/$defs/flag" },
                "twintails":              { "$ref": "#/$defs/flag" }
            }
        },

        "select_info": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "display_name":        { "type": "string" },
                "thumb":               { "$ref": "#/$defs/filename" },
                "group":               { "type": "string" },
                "visible_when_locked": { "type": "boolean", "default": true },
                "select_dlg":          { "$ref": "#/$defs/string_list" }
            }
        },

        "highlight": {
            "type": "object",
            "additionalProperties": false,

            "properties": {
                "default": { "$ref": "#/$defs/filter" },
                "mapping": {
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": { "^.*$": { "$ref": "#/$defs/filter" } }
                }
            }
        },

        "dryrun": { "$ref": "#/$defs/flag" },

        "hair_map": {
            "type": "object",
            "properties": {
                "all": { "type": "string", "default": "def" }
            },
            "patternProperties": {
                "^.*$": { "type": "string" }
            }
        },

        "giftname": { "$ref": "#/$defs/filename" },

        "pose_arms": {
            "crossed":             { "$ref": "#/$defs/pose_arm" },
            "left-down":           { "$ref": "#/$defs/pose_arm" },
            "left-rest":           { "$ref": "#/$defs/pose_arm" },
            "right-down":          { "$ref": "#/$defs/pose_arm" },
            "right-point":         { "$ref": "#/$defs/pose_arm" },
            "right-restpoint":     { "$ref": "#/$defs/pose_arm" },
            "steepling":           { "$ref": "#/$defs/pose_arm" },
            "def|left-down":       { "$ref": "#/$defs/pose_arm" },
            "def|right-def":       { "$ref": "#/$defs/pose_arm" }
        }
    },

    "$defs": {
        "pose": {
            "anyOf": [
                {
                    "if":   { "properties": { "mpm_type": { "const": 0 } } },
                    "then": { "type": "boolean" }
                },
                {
                    "if":   { "properties": { "mpm_type": { "const": 1 } } },
                    "then": {
                        "enum": [
                            "steepling", "crossed", "restleftpointright", "pointright", "down", "downleftpointright", "def|def"
                        ]
                    }
                }
            ]
        },

        "flag": { },

        "string_list": { "type": "array","items": { "type": "string" }, "default": null },

        "filter":  {
            "type": "object",
            "properties": {
                "default": { "type": "string" },
                "day":     { "type": "string" },
                "night":   { "type": "string" }
            }
        },

        "filename": { "type": "string", "pattern": "^[^./\\\\]*$" },

        "pose_arm": {
            "type": "object",
            "required": [ "tag", "layers" ],
            "properties": {
                "tag": { "type": "string", "pattern": "^arms-(?:left|right)-" },
                "layers": {
                    "type": "string", "pattern": "^(?:|\\*|(?:(?:0|1|5|10))(?:\\^(?:0|1|5|10))*)$"
                },
                "highlight": {
                    "type": "object",
                    "additionalProperties": false,

                    "properties": {
                        "default": { "$ref": "#/$defs/filter" },
                        "mapping": {
                            "type": "object",
                            "additionalProperties": false,
                            "patternProperties": { "^.*$": { "$ref": "#/$defs/filter" } }
                        }
                    }
                }
            }
        },

        "any": { "type": [ "number", "string", "boolean", "object", "array", "null" ] }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/unreleased/finale/Finale-gray-jacket-beige-turtleneck-sweater/mod_assets/monika/j/finale_clothes_jacket_gray_turtleneck_sweater_beige.json
{
    "__author": "Finale",
    "version": 3,
    "type": 2,
    "name": "finale_jacket_gray",
    "img_sit": "finale_jacket_gray",
    "pose_map": {
        "mpm_type": 0,
        "default": false,
        "use_reg_for_l": true,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true
    },
    "stay_on_start": true,
    "select_info": {
        "display_name": "Jacket (Gray)",
        "thumb": "finale_gray_jacket",
        "group": "clothes",
        "select_dlg": [
            "Perfect for a chilly day.",
            "Are we going somewhere, [player]?"
        ]
    },
    "giftname": "grayjacket",
    "pose_arms": {
        "crossed": {
            "tag": "crossed",
            "layers": "5^10"
        },
        "left-down": {
            "tag": "down",
            "layers": "0"
        },
        "left-rest": {
            "tag": "rest",
            "layers": "10"
        },
        "right-down": {
            "tag": "down",
            "layers": "0"
        },
        "right-point": {
            "tag": "point",
            "layers": "0"
        },
        "right-restpoint": {
            "tag": "restpoint",
            "layers": "10"
        },
        "steepling": {
            "tag": "steepling",
            "layers": "10"
        },
        "def|left-def": {
            "tag": "def",
            "layers": "10"
        },
        "def|right-def": {
            "tag": "def",
            "layers": "5^10"
        }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-bralette red ruffles/mod_assets/monika/j/briaryoung_clothes_bralette_red_ruffles.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 2,
    "name": "briaryoung_bralette_red_ruffles",
    "img_sit": "briaryoung_bralette_red_ruffles",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "bare-shoulders": true
    },
    "select_info": {
        "display_name": "Bralette (Red, Ruffles)",
        "thumb": "briaryoung_bralette_red_ruffles",
        "group": "clothes",
        "select_dlg": [
            "How do I look?",
            "Stunning~",
            "Like what you see?"
        ]
    },
    "giftname": "braletteredruffles",
    "pose_arms": {}
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/orca/Orcaramelo-miku/mod_assets/monika/j/orcaramelo_clothes_hatsune_miku.json
{
    "__author": "Orcaramelo",
    "version": 3,
    "type": 2,
    "name": "orcaramelo_hatsune_miku",
    "img_sit": "orcaramelo_hatsune_miku",
    "pose_map": {
        "mpm_type": 0,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true
    },
    "stay_on_start": true,
    "ex_props": {
        "desired-hair-prop": "twintails",
        "costume": "o31",
        "cosplay": true,
        "bare-shoulders": true
    },
    "select_info": {
        "display_name": "Hatsune Miku",
        "thumb": "orcaramelo_hatsune_miku",
        "group": "clothes",
        "select_dlg": [
            "The first sound of the future!",
            "Ready for the stage!",
            "Only missing a leek..."
        ]
    },
    "pose_arms": {
        "crossed": {
            "tag": "crossed",
            "layers": "5^10"
        },
        "left-down": {
            "tag": "down",
            "layers": "0"
        },
        "left-rest": {
            "tag": "rest",
            "layers": "10"
        },
        "right-down": {
            "tag": "down",
            "layers": "0"
        },
        "right-point": {
            "tag": "point",
            "layers": "0"
        },
        "right-restpoint": {
            "tag": "restpoint",
            "layers": "10"
        },
        "steepling": {
            "tag": "steepling",
            "layers": "10"
        },
        "def|left-def": {
            "tag": "def",
            "layers": "10"
        },
        "def|right-def": {
            "tag": "def",
            "layers": "5^10"
        }
    },
    "giftname": "hatsunemikucosplay"
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/finale/Finale-Shirt-HappyFace/mod_assets/monika/j/finale_clothes_putonahappyface_shirt.json
{
    "__author": "Finale",
    "ex_props": {
        "bare-shoulders": true,
        "home": true,
        "date": true
    },
    "version": 3,
    "type": 2,
    "name": "finale_putonahappyface_shirt",
    "img_sit": "finale_putonahappyface_shirt",
    "pose_map": {
        "mpm_type": 0,
        "default": false,
        "use_reg_for_l": true,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true
    },
    "stay_on_start": true,
    "select_info": {
        "display_name": "Shirt (Put on a happy face)",
        "thumb": "finale_putonahappyface_shirt",
        "group": "clothes",
        "select_dlg": [
            "Come on [player], where's your happy face?",
            "What can I say? Musical puns are my forte~"
        ]
    },
    "giftname": "putonahappyfaceshirt",
    "pose_arms": {
        "crossed": {
            "tag": "crossed",
            "layers": "5"
        },
        "left-down": {
            "tag": "down",
            "layers": "0"
        },
        "left-rest": {
            "tag": "rest",
            "layers": "10"
        },
        "right-down": {
            "tag": "down",
            "layers": "0"
        },
        "right-point": {
            "tag": "point",
            "layers": "0"
        },
        "right-restpoint": {
            "tag": "restpoint",
            "layers": "10"
        },
        "steepling": {
            "tag": "steepling",
            "layers": "10"
        },
        "def|left-def": {
            "tag": "def",
            "layers": "10"
        },
        "def|right-def": {
            "tag": "def",
            "layers": "5"
        }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-cross-strap-bikini-green/mod_assets/monika/j/briaryoung_cross-strap-bikini-green.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 2,
    "name": "briaryoung_cross_strap_bikini_green",
    "img_sit": "briaryoung_cross_strap_bikini_green",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "compat-downtiedstrand": true
    },
    "select_info": {
        "display_name": "Cross Strap Bikini (Green)",
        "thumb": "briaryoung_cross_strap_bikini_green",
        "group": "clothes",
        "select_dlg": [
            "Are we going to the beach?"
        ]
    },
    "giftname": "crossstrapbikinigreen",
    "pose_arms": {}
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-tshirt-jurassic-park/mod_assets/monika/j/briaryoung_clothes_tshirt_jurassic_park.json
{
    "__author": "Briar Young",
    "ex_props": {
        "home": true
    },
    "version": 3,
    "type": 2,
    "name": "briaryoung_tshirt_jurassic_park",
    "img_sit": "briaryoung_tshirt_jurassic_park",
    "pose_map": {
        "mpm_type": 0,
        "default": false,
        "use_reg_for_l": true,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true
    },
    "stay_on_start": true,
    "select_info": {
        "display_name": "T-Shirt (Jurassic Park)",
        "thumb": "briaryoung_tshirt_jurassic_park",
        "group": "clothes",
        "select_dlg": [
            "Life finds a way...",
            "Does this make me a clever girl?",
            "Clever [boy]~",
            "Welcome to Jurassic Park!",
            "I promise I won't bite~"
        ]
    },
    "giftname": "tshirtjurassicpark",
    "pose_arms": {
        "crossed": {
            "tag": "crossed",
            "layers": "5"
        },
        "left-down": {
            "tag": "down",
            "layers": "0"
        },
        "left-rest": {
            "tag": "rest",
            "layers": "10"
        },
        "right-down": {
            "tag": "down",
            "layers": "0"
        },
        "right-point": {
            "tag": "point",
            "layers": "0"
        },
        "right-restpoint": {
            "tag": "restpoint",
            "layers": "10"
        },
        "steepling": {
            "tag": "steepling",
            "layers": "10"
        },
        "def|left-def": {
            "tag": "def",
            "layers": "10"
        },
        "def|right-def": {
            "tag": "def",
            "layers": "5"
        }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/finale/Finale-turtleneck-sweater-beige/mod_assets/monika/j/finale_clothes_turtleneck_sweater_beige.json
{
    "__author": "Finale",
    "version": 3,
    "type": 2,
    "name": "finale_turtleneck_sweater_beige",
    "img_sit": "finale_turtleneck_sweater_beige",
    "pose_map": {
        "mpm_type": 0,
        "default": false,
        "use_reg_for_l": true,
        "p1": true,
        "p2": true,
        "p3": true,
        "p4": true,
        "p5": true,
        "p6": true,
        "p7": true
    },
    "stay_on_start": true,
    "select_info": {
        "display_name": "Turtleneck Sweater (Beige)",
        "thumb": "finale_turtleneck_sweater_beige",
        "group": "clothes",
        "select_dlg": [
            "So cozy~",
            "Perfect for snuggling!"
        ]
    },
    "giftname": "beigeturtlenecksweater",
    "pose_arms": {
        "crossed": {
            "tag": "crossed",
            "layers": "5^10"
        },
        "left-down": {
            "tag": "down",
            "layers": "0"
        },
        "left-rest": {
            "tag": "rest",
            "layers": "10"
        },
        "right-down": {
            "tag": "down",
            "layers": "0"
        },
        "right-point": {
            "tag": "point",
            "layers": "0"
        },
        "right-restpoint": {
            "tag": "restpoint",
            "layers": "10"
        },
        "steepling": {
            "tag": "steepling",
            "layers": "10"
        },
        "def|left-def": {
            "tag": "def",
            "layers": "10"
        },
        "def|right-def": {
            "tag": "def",
            "layers": "5^10"
        }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-heart-cut-bikinis/mod_assets/monika/j/briaryoung_clothes_heart_cut_bikini_white.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 2,
    "name": "briaryoung_heart_cut_bikini_white",
    "img_sit": "briaryoung_heart_cut_bikini_white",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "compat-downtiedstrand": true,
        "bare-shoulders": true,
        "wet": true
    },
    "select_info": {
        "display_name": "Heart-Cut Bikini (White)",
        "thumb": "briaryoung_heart_cut_bikini_white",
        "group": "clothes",
        "select_dlg": [
            "I love this look!"
        ]
    },
    "giftname": "heartcutbikiniwhite",
    "pose_arms": {}
}
