=== Monika-After-Story/MonikaModDev/schemas/v3/hair.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",

    "title": "Hair",
    "description": "Monika After Story Mod hair JSON schema",

    "type": "object",
    "additionalProperties": false,
    "required": [
        "version",
        "type",
        "name",
        "img_sit",
        "pose_map"
    ],

    "properties": {
        "__author": { "$ref": "#/$defs/any" },

        "version": { "const": 3 },
        "type":    { "const": 1 },
        "name":    { "type": "string" },
        "img_sit": { "$ref": "#/$defs/filename" },

        "pose_map": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mpm_type":      { "type": "integer" },
                "default":       { "$ref": "#/$defs/pose" },
                "l_default":     { "$ref": "#/$defs/pose" },
                "use_reg_for_l": { "type": "boolean", "default": false }
            },
            "patternProperties": {
                "p[0-7]": { "$ref": "#/$defs/pose" }
            }
        },

        "stay_on_start": { "type": "boolean", "default": false },

        "ex_props": {
            "type": "object",
            "default": { },
            "properties": {
                "excluded-clothes-props": { "$ref": "#/$defs/string_list" },
                "no-tails":               { "$ref": "#/$defs/flag" },
                "required-clothes-prop":  { "type": "string" },
                "ribbon":                 { "$ref": "#/$defs/flag" },
                "ribbon-off":             { "$ref": "#/$defs/flag" },
                "ribbon-restore":         { "$ref": "#/$defs/flag" },
                "tiedstrand":             { "$ref": "#/$defs/flag" },
                "twintails":              { "$ref": "#/$defs/flag" }
            }
        },

        "select_info": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "display_name":        { "type": "string" },
                "thumb":               { "$ref": "#/$defs/filename" },
                "group":               { "type": "string" },
                "visible_when_locked": { "type": "boolean", "default": true },
                "select_dlg":          { "$ref": "#/$defs/string_list" }
            }
        },

        "highlight": {
            "type": "object",
            "additionalProperties": false,

            "properties": {
                "default": { "$ref": "#/$defs/filter" },
                "mapping": {
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": { "^.*$": { "$ref": "#/$defs/filter" } }
                }
            }
        },

        "dryrun": { "$ref": "#/$defs/flag" },

        "unlock": { "type": "boolean", "default": true }
    },

    "$defs": {
        "pose": {
            "if": { "properties": { "mpm_type": 0 } },
            "then": { "type": "boolean" },
            "else": {
                "enum": [
                    "steepling", "crossed", "restleftpointright", "pointright", "down", "downleftpointright", "def|def"
                ]
            }
        },

        "flag": { },

        "string_list": { "type": "array","items": { "type": "string" }, "default": null },

        "filter":  {
            "type": "object",
            "properties": {
                "default": { "type": "string" },
                "day":     { "type": "string" },
                "night":   { "type": "string" }
            }
        },

        "filename": { "type": "string", "pattern": "^[^./\\\\]*$" },

        "any": { "type": [ "number", "string", "boolean", "object", "array", "null" ] }
    }
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-hair-pack-1/mod_assets/monika/j/briaryoung_hair_pigtails.json
{
    "__author": "Briar Young",
    "version": 3,
    "type": 1,
    "name": "briaryoung_pigtails",
    "img_sit": "briaryoung_pigtails",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "ribbon": true,
        "twintails": true
    },
    "select_info": {
        "display_name": "Pigtails",
        "thumb": "briaryoung_pigtails",
        "group": "hair"
    },
    "unlock": true
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-chika fujiwara/mod_assets/monika/j/briaryoung_hair_down_straight_bangs.json
{
    "__author": "briaryoung",
    "version": 3,
    "type": 1,
    "name": "briaryoung_down_straight_bangs",
    "img_sit": "briaryoung_down_straight_bangs",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "no-tails": true,
        "straight-bangs": true
    },
    "select_info": {
        "display_name": "Down (Straight Bangs)",
        "thumb": "briaryoung_down_straight_bangs",
        "group": "hair"
    },
    "unlock": true
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/orca/Orcaramelo-hairs/mod_assets/monika/j/orcaramelo_hair_twinbun.json
{
    "__author": "Orcaramelo",
    "version": 3,
    "type": 1,
    "name": "orcaramelo_twinbun",
    "img_sit": "orcaramelo_twinbun",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "ribbon": true,
        "twintails": true
    },
    "select_info": {
        "display_name": "Twin Bun",
        "thumb": "orcaramelo_twinbun",
        "group": "hair"
    },
    "unlock": true
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/orca/Orcaramelo-hairs/mod_assets/monika/j/orcaramelo_hair_bunbraid.json
{
    "__author": "Orcaramelo",
    "version": 3,
    "type": 1,
    "name": "orcaramelo_bunbraid",
    "img_sit": "orcaramelo_bunbraid",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "ribbon": true,
        "braidstrand": true,
        "bunbraid": true
    },
    "select_info": {
        "display_name": "Bun Braid",
        "thumb": "orcaramelo_bunbraid",
        "group": "hair"
    },
    "unlock": true
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-hair-pack-1/mod_assets/monika/j/briaryoung_hair_down_with_bun.json
{
    "__author": "Briar Young",
    "version": 3,
    "type": 1,
    "name": "briaryoung_hair_down_with_bun",
    "img_sit": "briaryoung_hair_down_with_bun",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "select_info": {
        "display_name": "Hair Down (Bun)",
        "thumb": "briaryoung_hair_down_with_bun",
        "group": "hair"
    },
    "unlock": true
}

=== Monika-After-Story/MonikaModDev/spritepacks/released/briaryoung/briaryoung-hair-pack-1/mod_assets/monika/j/briaryoung_hair_down_ponytail.json
{
    "__author": "Briar Young",
    "version": 3,
    "type": 1,
    "name": "briaryoung_hair_down_ponytail",
    "img_sit": "briaryoung_hair_down_ponytail",
    "pose_map": {
        "mpm_type": 0,
        "default": true,
        "use_reg_for_l": true
    },
    "stay_on_start": true,
    "ex_props": {
        "ribbon": true,
        "twintails": true
    },
    "select_info": {
        "display_name": "Hair Down (Ponytail)",
        "thumb": "briaryoung_hair_down_ponytail",
        "group": "hair"
    },
    "unlock": true
}
